spring.application.name=MatGourmand
app.auth.token-secret-base64=Q2hhbmdlVGhpc1RvQVNlY3VyZUJhc2U2NEtleUZvclByb2R1Y3Rpb24xMjM0NQ==
app.auth.access-token-expiration-millis=86400000
app.auth.issuer=matgourmand
app.seed.enabled=false
springdoc.swagger-ui.path=/swagger-ui.html
